apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  namespace: flask-app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "postgres" 
        - name: POSTGRES_PASSWORD
          value: "password" 
        - name: POSTGRES_DB
          value: "mydatabase" 

